summary: ''
description: ''
lock: '!inline f/monitor/get_settings.script.lock'
kind: script
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties: {}
  required: []
